#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 19 15:43:10 2022

@author: aleksander

Program for generating initial Guesses for the Quasiparticle solver.
It simply looks for where the DOS attains a large value and can be constrained
in an energy interval and a timeinterval

"""
import numpy as np
import sys
import os
import numba as nb
from Zandpack.Loader import flexload

outfile = "QuasiParticle_Solver_Input_t_and_E_pairs" # Fixed by the Adiabatic code
args    = sys.argv[1:]
options = {'Emin':'-1.0',
           'Emax':'+1.0',
           'DOS_min':'20.0',
           'DOS_max':'1000000.0',
           'file':'SteadyStateFile',
           }

if '--help' in args:
    print('Keywords and default values. Assign with "keyword=value" argument after dos2qp_guess command (no spaces!)')
    for keys,values in options.items():
        print(keys, ':', values)
    exit()




for a in args:
    split = a.replace(' ', '').split('=')
    options.update({split[0]:split[1]})

path       = args[0].replace(' ', '').split('=')[1]
os.chdir(path)
new_folder = os.getcwd()
sys.path.append(new_folder)

@nb.njit
def make_TE_grid(times, eg):
    nt, ne = len(times), len(eg)
    
    tout = np.zeros((nt, ne))
    eout = np.zeros((nt, ne))
    for it in range(nt):
        for ie in range(ne):
            tout[it,ie] = times[it]
            eout[it,ie]  = eg[ie]
    return tout, eout

Calc  = flexload(options['file'] + '.npz')
DOS   = Calc["DOS"]
times = Calc["times"]
eg    = Calc["Eg_DOS"]
T,E   = make_TE_grid(times, eg)

dmin,dmax = float(options['DOS_min']), float(options['DOS_max']) 
emin,emax = float(options['Emin']), float(options['Emax'])

from Initial import t0,t1
tmin,tmax = t0,t1#float(options['tmin']), float(options['tmax'])

i,j       = np.where((DOS>dmin)*(DOS<dmax)*(T>tmin)*(T<tmax)*(E>emin)*(E<emax))
tout = T[i,j]
eout = E[i,j]
T_E  = np.zeros((len(i), 2))
print('Found', len(T_E), 'points for QP guess')
T_E[:,0] = tout
T_E[:,1] = eout
np.save(outfile+'.npy', T_E)

