#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 14 14:47:00 2022

@author: aleksander

Set the savetime of a calculation specified in
the two positional arguments

do a lossydm --help to see usage.

"""

import sys
import os
import numpy as np
from Zandpack.plot import DM
from time import sleep
import subprocess
args = sys.argv[1:]
path       = args[0].replace(' ', '').split('=')[1]
os.chdir(path)
new_folder = os.getcwd()
sys.path.append(new_folder)
options = {'folder':'ABC_save',
           "tol":"0.5e-7",
           "delete":"True",
           "interp":"linear",
           "usexz":"True"
           }
if '--help' in args:
    print("Args: ")
    print(options)
    exit()

for a in args:
    if 'command' not in a:
        split = a.replace(' ', '').split('=')
    else:
        split = a.split('=')
    options.update({split[0]:split[1]})


tdm, dm = DM([options["folder"]])

ti    = tdm[0] + 0.0
dmi   = dm[0].copy()
tout  = [ti]
dmout = [dmi]
inds  = []
nt    = len(tdm)
tol   = float(options["tol"])

if options["interp"]=="step":
    print("step interpolation")
    for i in range(1,nt):
        if np.abs(dmi-dm[i]).max()>tol:
            ti  = tdm[i] + 0.0
            dmi =  dm[i].copy()
            tout.append(ti)
            dmout.append(dmi)
    tout  = np.array(tout)
    dmout = np.array(dmout)
    
elif options["interp"]=="linear":
    print("linear interpolation")
    from numba import njit
    @njit
    def absmax(A, tv, idx):
        M     = 0.0
        i0    = idx[0]
        i1    = idx[-1]
        A0    = A[i0]
        A1    = A[i1]
        dAdt  = A1 - A0
        dAdt /= (tv[i1] - tv[i0])
        
        for i in range(len(idx)):
            I    = idx[i]
            dt   = (tv[I] - tdm[i0])
            diff = np.abs(A[I] - (A0 + dt * dAdt)).max()
            M    = max(M, diff)
        return M
    i0 = 0
    # print("len before: " + str(len(tdm)))
    while i0 < len(tdm):
        i1 = i0 +2
        if i1 >= len(tdm):
            break
        idx = np.arange(i0,i1+1)
        #assert np.abs(absmax(dm, tdm, idx) - np.abs(dm[i0:i1+1] - (dm[i0] + (tdm[i0:i1+1] - tdm[i0])[:, None, None, None] * (dm[i1]-dm[i0])/(tdm[i1] - tdm[i0]))
        #             ).max()) < 1e-10
        while absmax(dm, tdm, idx) < float(options["tol"]):
            i1 += 1
            idx = np.arange(i0,i1+1)
        i0 = i1  -1
        if i0 not in inds:
            # Edge case with last index in the calculatiuon i think
            inds  += [i0]
            dmout += [dm[i0]]
            tout  += [tdm[i0]]
    if len(tdm)-1 not in inds:
        dmout += [dm[len(tdm)-1]]
        tout  += [tdm[len(tdm)-1]]
    # print("len after: " + str(len(tout)))

else:
    # print("D")
    assert 1 == 0, "The interp keyword was not recognized."

dmout = np.array(dmout)
tout  = np.array(tout)
print(tout.min(), tout.max())
print(tdm.min(), tdm.max())


print("From "+str(nt) + " to " + str(len(tout)) + " points ")
# import matplotlib.pyplot as plt
#plt.plot(tout, dmout[:, 0, 25,25])
#plt.plot(tdm, dm[:, 0, 25,25])
# y2 = np.interp(tdm, tout, dmout[:, 0, 25,25].real)
# plt.plot(tdm, dm[:, 0, 25,25])
# plt.plot(tdm, dm[:, 0, 25,25].real - y2)
# plt.show()
# assert 1 == 0

# Transpose of dm for better time-locality in the data, which means more similar numbers
if options["usexz"] == "False":
    np.savez_compressed(options["folder"]+"/LossyDensityMatrix.npz", 
                        tdm = tout, dm = dmout.transpose(1,2,3,0), 
                        t_orig = tdm, tol = tol)
else:
    npz_path = options["folder"] + "/LossyDensityMatrix.npz"
    np.savez(npz_path,  # uncompressed, so xz has raw bytes to work with
             tdm=tout, dm=dmout.transpose(1,2,3,0),
             t_orig=tdm, tol=tol)
    subprocess.run(["xz", "-9", "-e", "-T0", "-f", npz_path], check=True)
assert ("LossyDensityMatrix.npz.xz" in os.listdir(options["folder"]) ) or ("LossyDensityMatrix.npz" in os.listdir(options["folder"]))

if options["usexz"]=="True":
    if options["delete"]=="True":
        print("Deleting previous DMs from "+options["folder"])
        os.system("rm "+options["folder"]+"/DM*.npy")
        os.system("rm "+options["folder"]+"/DM*.npz")
        os.system("rm "+options["folder"]+"/LossyDensityMatrix.npz")
if options["usexz"]=="False":
    if options["delete"]=="True":
        print("Deleting previous DMs from "+options["folder"])
        os.system("rm "+options["folder"]+"/DM*.npy")
        os.system("rm "+options["folder"]+"/DM*.npz")
        os.system("rm "+options["folder"]+"/LossyDensityMatrix.npz.xz")


    


















