#!/usr/bin/env python3
print_string = """
Minimal floquet photo-assisted current from Viljas and Cuevas, 2007.

    I = (e/h) int_0^{hw} dE  sum_{k,l} Tr[G(E) Gam_R^(k) G^+(E) Gam_L^(l)] (f_L^(l) - f_R^(k))

    [Gam^(l)]_{m,n} = J_{m+l}(a_W) J_{n+l}(a_W) Gam(E - lhw)
    [Sig]_a{m,n}     = sum_l J_{m+l}(eVa/hw) J_{n+l}(eVa/hw) Sig(E - lhw)

    For use with the Zandpack files used also for the nozand/zand programs.

    e -> (norb, norb) array.  Energies in eV, current in e/fs.
"""



import numpy as np
from scipy.integrate import quad
from scipy.special import jv
from Zandpack.FittedSelfEnergy import from_saved_file
from Zandpack.Help import TDHelper
import sys, os
from mpi4py import MPI
from Zandpack.td_constants import hbar

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()
if rank == 0:
    print(print_string)
    print("Returning current in units of e/fs")
args    = sys.argv[1:]
options = {"device":"ABC",
           "hw":"hw.npy",
           "ampl":"ampl.npy",
           "voltage":"0.0",
           "NPHOT":"3",
           "outfile":"tg_ext.npz",
           "kT":"0.025",
           "epsrel":"1e-7",
           "epsabs":"1e-7",
           "limit":"800",
           "Wmat":"None",
           "Wmat_fact":'1.0',
           "Wideband":"False",
           "Wideband_fact":"1.0",
           }
if "--help" in args:
    for kw in options.keys():
        print(options[kw])
    sys.exit()

for a in args:
    split = a.replace(' ', '').split('=')
    options.update({split[0]:split[1]})
if rank == 0:
    print("Writing results to " + options["outfile"].replace(".npz","") + ".npz")
    print("Given parameters:")
    for kw in options.keys():
        print(kw, " = ", options[kw])
    print("#processes = ", size)
    print("Start....")

path = args[0].replace(' ', '').split('=')[1]
os.chdir(path)
new_folder = os.getcwd()
sys.path.append(new_folder)
mode  = 'fitted'
name  = options["device"]
H0    = np.load(name+ "/Arrays/SCF_Hlast_Ortho.npy")
_SE   = from_saved_file(name+"/Arrays")
Hlp   = TDHelper(name, valid_ranks = [i for i in range(size)])
if options["Wideband"]!="True":
    class dummy_se:
        def __init__(self, fitSE, kidx):
            self.SE   = fitSE
            self.kidx = kidx
            self.no   = fitSE.Coeffs.shape[-1]
        def self_energy(self, E, k = np.array([0.0, 0.0, 0.0])):
            _E = np.array([E])
            return self.SE.evaluate(_E, noopt=False)[self.kidx, 0]
else:
    class dummy_se:
        def __init__(self, fitSE, kidx):
            self.SE   = fitSE
            self.kidx = kidx
            self.no   = fitSE.Coeffs.shape[-1]
            self.make_gamma()
        def self_energy(self, E, k = np.array([0.0, 0.0, 0.0])):
            G = self.gamma
            return (-1j/2) * G
        def make_gamma(self):
            Emin, Emax, N = -5.0, 5.0, 252
            Eg = np.linspace(Emin, Emax,N)
            dE = Eg[1] - Eg[0]
            Eg = Eg[1:]*0.5 + Eg[:-1]*0.5
            G  = np.zeros((self.no, self.no),dtype=complex)
            for i in range(N-1):
                _Ei = np.array([Eg[i]])
                SE = self.SE.evaluate(_Ei, noopt=False)[self.kidx, 0]
                g  = 1j*(SE - SE.conj().T)
                G += g
            G*=(dE * float(options["Wideband_fact"]))
            G*=(1/(Emax-Emin))
            self.gamma = G

kidx  = 0
SE    = [dummy_se(se, kidx) for se in _SE]
hw    = options["hw"].split(",")
hw1, hw2, hwN = [float(hwi) for hwi in hw]
hwN = int(hwN)
hw   = np.linspace(hw1, hw2, hwN)
ampl = options["ampl"].split(",")
ampl1, ampl2, amplN = [float(ai) for ai in ampl]
amplN = int(amplN)
ampl = np.linspace(ampl1, ampl2, amplN)
Wmat = None
if options["Wmat"]!="None":
    P1 = np.average(Hlp.pos_elecorbs[0],axis=0)
    P2 = np.average(Hlp.pos_elecorbs[1],axis=0)
    drc= P2 - P1; drc *= 1/np.linalg.norm(drc)
    Po = (Hlp.orb_pos - P1).dot(drc) 
    X0 = Po.min(); X1 = Po.max()
    def ramp_field(r,t):
        _b1 =  1.0
        _b2 = -1.0
        X = (r - P1).dot(drc); F = _b1 + (_b2 - _b1) *(X - X0)/(X1 - X0)
        return F
    _no  = H0.shape[-1]
    Wmat = Hlp.approxfield2mat(0.0, ramp_field, orthogonal=True).reshape(_no, _no).copy()
    Wmat*= 0.5
def fermi(e, mu, kT):
    return 1.0 / (1.0 + np.exp(np.clip((e - mu) / kT, -400.0, 400.0)))
def integrand(e, V, H0, sig_L, sig_R, hw,
              aL=0.0, aR=0.0, nflq=5, nphot=14, 
              eF=0.0, kT=5e-3, eta=0.5):
    """sum_{k,l} Tr[Gr Gam_R^(k) Ga Gam_L^(l)] (f_L^(l) - f_R^(k)) at energy e."""
    ms = np.arange(-nflq,  nflq +1)
    ls = np.arange(-nphot, nphot+1)
    nb, D = H0.shape[0], len(ms)

    muL, muR = eF + eta * V, eF - (1.0 - eta) * V
    uL, uR = muL - eF, muR - eF
    # --- retarded Green function ---
    sigL = np.zeros((2 * nphot +1, nb, nb),dtype=complex)
    sigR = np.zeros((2 * nphot +1, nb, nb),dtype=complex)
    vL_v = np.zeros((len(ls), len(ms)))
    vR_v = np.zeros((len(ls), len(ms)))
    for il,l in enumerate(ls):
        vL  = np.array([jv(m + l, aL) for m in ms])
        vR  = np.array([jv(m + l, aR) for m in ms])
        vL_v[il], vR_v[il] = vL, vR
        sigL[il], sigR[il] = sig_L(e-uL-l*hw), sig_R(e-uR-l*hw)
    sig =np.einsum("lm,ln,lij->minj",vL_v,vL_v,sigL,optimize=True)
    sig+=np.einsum("lm,ln,lij->minj",vR_v,vR_v,sigR,optimize=True)
    # Overwrite sigma with gamma
    for il,l in enumerate(ls):
        sigL[il] -= sigL[il].T.conj()
        sigL[il] *= 1j
        sigR[il] -= sigR[il].T.conj()
        sigR[il] *= 1j
    gr  = np.kron(np.diag(e + 0.0j + ms * hw), np.eye(nb))
    for i in range(D):
        gr[i*nb:(i+1)*nb, i*nb:(i+1)*nb] -= H0
    if Wmat is not None:
        _w = Wmat*((aL-aR)*hw*0.5)
        _wc = _w.T.conj()
        # Factor of 2 depends on the definition
        for i in range(0, D-1):
            b1 = slice( i*nb,    (i+1)*nb)
            b2 = slice((i+1)*nb, (i+2)*nb)
            gr[b1,b2] -= _w  
            gr[b2,b1] -= _wc
    gr -= sig.reshape(len(ms)*nb, len(ms)*nb)
    gr = np.linalg.inv(gr)
    ga = gr.T.conj()
    total = 0.0
    for ik, k in enumerate(ls):
        vR = np.array([jv(m + k, aR) for m in ms])
        gR = sigR[ik]
        fR = fermi(e - k * hw, muR, kT)
        W4 = np.einsum("minj,n,b,jl,blcv -> micv",
                       gr.reshape((nflq*2+1), nb, (nflq*2+1), nb),
                       vR, vR, gR,
                       ga.reshape((nflq*2+1), nb, (nflq*2+1), nb),
                       optimize=True)
        occ_v,occ_i = [],[]
        for ic, l in enumerate(ls):
            occ = fermi(e - l * hw, muL, kT) - fR
            if abs(occ) < 1e-14:
                continue
            occ_v.append(occ)
            occ_i.append(ic)
        if len(occ_v)<1:
            continue
        occ_v = np.array(occ_v); occ_i = np.array(occ_i)
        vL_ml = np.array([[jv(m + l, aL) for m in ms] for l in ls[occ_i]]).T.copy()
        total+= np.einsum("minj,nl,ml,l,lji->", W4, vL_ml, vL_ml, occ_v, sigL[occ_i], optimize=True).real
    return total
def current(V, **kw):
    val,err = quad(lambda e: integrand(e, V, **kw), 0.0, kw["hw"], 
                   epsabs=float(options["epsabs"]), 
                   epsrel=float(options["epsrel"]), 
                   limit=int(options["limit"]))
    val *= 1 / (hbar*2*np.pi)
    err *= 1 / (hbar*2*np.pi)
    return val,err
if __name__ == "__main__":
    IJ = np.array([(i, j) for i in range(hwN) for j in range(amplN)])
    ntasks = len(IJ)
    # --- shared task counter on rank 0 -------------------------------------
    if rank == 0:
        counter = np.zeros(1, dtype=np.int64)
        win = MPI.Win.Create(counter, disp_unit=8, comm=comm)
    else:
        win = MPI.Win.Create(None, comm=comm)
    _one, _got = np.ones(1, dtype=np.int64), np.zeros(1, dtype=np.int64)
    def next_task():
        """Atomically claim the next index. Returns ntasks when exhausted."""
        win.Lock(0, MPI.LOCK_SHARED)
        win.Fetch_and_op(_one, _got, 0, 0, op=MPI.SUM)
        win.Unlock(0)
        return int(_got[0])
    # --- work loop ---------------------------------------------------------
    cur = np.zeros((hwN, amplN))
    err = np.zeros((hwN, amplN))
    ndone = 0
    while True:
        t = next_task()
        if t >= ntasks:
            break
        i, j = IJ[t]
        par = dict(H0=H0[kidx],
                   sig_L=lambda e: SE[0].self_energy(e),
                   sig_R=lambda e: SE[1].self_energy(e),
                   hw=hw[i], kT=float(options["kT"]),
                   aL=ampl[j] / hw[i], aR=-ampl[j] / hw[i],
                   nflq=int(options["NPHOT"]), nphot=int(options["NPHOT"]))
        cur[i, j], err[i, j] = current(float(options["voltage"]), **par)
        ndone += 1
        print(f"rank {rank}: local {ndone}, global {t+1}/{ntasks}", flush=True)
    win.Free()
    # --- collect: one call, no files, no sleep ------------------------------
    tot_cur = np.zeros_like(cur) if rank == 0 else None
    tot_err = np.zeros_like(err) if rank == 0 else None
    comm.Reduce(cur, tot_cur, op=MPI.SUM, root=0)
    comm.Reduce(err, tot_err, op=MPI.SUM, root=0)
    if rank == 0:
        np.savez_compressed(options["outfile"],
                            cur=tot_cur,
                            err=tot_err,
                            hw=hw,
                            ampl=ampl
                            )
