#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 14 16:15:03 2022

@author: aleksander
"""
# import os
# f_loc = __file__[:-10]

# string = ''
# nl = '\nl'

# string += 'Folder location: '   + f_loc + nl
# string += 'Adiabatic: Adiabatic transport, "Adiatitic --help for more info'
# string += 'Basischange: Basischange transport, "Basischange --help" for more info'