#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 29 10:43:43 2022

@author: aleksander
"""

import sys
import os
import numpy as np
import sisl


args = sys.argv[1:]
print('TDvisualisation Program Start')
print('')
print('sys.argv:', sys.argv)
print('')

# Default values
# 
options = {'ts':'times.npy',
           'basis_dir': 'Device',
           'mode':'DM',
           'TDT_file': 'TDT_file',
           'TDTout_file':'TDT_file_save',
           }

if '--help' in args:
    print('Keywords and default values. Assign with "keyword=value" argument after TDvisualisation command (no spaces!)')
    for keys,values in options.items():
        print(keys, ':', values)
    exit()

for a in args:
    split = a.replace(' ', '').split('=')
    options.update({split[0]:split[1]})

path       = args[0].replace(' ', '').split('=')[1]
os.chdir(path)
new_folder = os.getcwd()
sys.path.append(new_folder)
