#!/bin/bash
#SBATCH --partition=general # This is the default partition
#SBATCH --qos=long
#SBATCH --job-name=3E62
#SBATCH --output=run.out
#SBATCH --error=run.error
#SBATCH --cpus-per-task=2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=47:00:00
#SBATCH --mem=50G
#SBATCH --mail-user=aleksander.bach@dipc.org
#SBATCH --mail-type=ALL

# module load Siesta/5.0.1-foss-2023a
module load intel
module load Anaconda3

conda activate /scratch/abalo/conda-env/scc-test

export PATH="/scratch/abalo/dftbplus-24.1.x86_64-linux/bin:$PATH"
export PATH="/scratch/abalo/Code/PythonModules/Zandpack/Zandpack/cmdtools:$PATH"
export PATH="/scratch/abalo/Code/PythonModules/Zandpack/Zandpack/mpi:$PATH"
export OMP_NUM_THREADS=2
export NUMBA_NUM_THREADS=2
export MKL_NUM_THREADS=2
export LINEARIZE="True"
mpirun zand Dir=$PWD file=3E_new > RUN.out
